### ISSUE TITLE
Javascript  usage help request

### ISSUE THREAD

**Issue by ashnur** [typeetfunc/datascript-mori#1]
Is there a way to query the db and get back mori values? Instead of javascript? Or should I just convert these values back somehow? Am I missing something? My goal would be to use the db as my state and immutable values even when it's not exactly the db I am working on, just results from it.

**Comment by kristianmandrup** [comment]
Yeah, looks promising but no real docs... except for the export functions in [core](https://github.com/typeetfunc/datascript-mori/blob/master/src/datascript_mori/core.cljs) and a few tests such as this [node usage](https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test_include_node.js) example.

``` js
var datascript_mori = require('./datascript-mori');
var d = datascript_mori.datascript.js;
var conn = d.create_conn();
d.transact(conn, [[":db/add", -1, "name", "Ivan"]]);
var res = d.q("[:find ?e ?v :where [?e \"name\" ?v]]", d.db(conn));
var res_str = JSON.stringify(res);
console.log(res_str); // => [[1, "Ivan"]]
```

**Comment by ashnur** [comment]
Yeah, but `d.q` returns mutable stuff, not immutable.

**Comment by kristianmandrup** [comment]
Yeah, there is no integration in this lib. Just a simple wrapper to include both datascript and mori. You/we will have to do your own integration I'm afraid :P
I'm experimenting with using React Native with Typescript and Datascript myself ;)

**Comment by typeetfunc** [comment]
@ashnur @kristianmandrup to get mori values use `datascript_mori.datascript.core` API - its a pure clojurescript API without any JS conversions. Example

``` JavaScript
import {datascript as ds, mori, helpers} from 'datascript-mori'
const {core: d} = ds
const {hashMap, vector, get, equals, parse} = mori
const {DB_AFTER, DB_BEFORE, TX_DATA, TX_META} = helpers
const db = d.empty_db()
const newDb = d.db_with(db, vector(
  hashMap(
    DB_ID, 2,
    "name", "Igor",
    "age", 35
  )
)) // use shortcut tx
const withIvan = d.db_with(newDb, vector(
  vector(DB_ADD, 1, "name", "Ivan"),
  vector(DB_ADD, 1, "age", 17)
)) // use full tx definition
const resOfQuery = d.q(parse('[:find ?n ?a :where [?e "name" ?n] [?e "age" ?a]]'), withIvan);
// in resOfQuery mori data structures
```

You can also use transact api, but i am prefer [stream interfaces](https://github.com/typeetfunc/rx-datascript).
Also to minimize boilerplate and runtime overhead of parsing EDN, I have written [babel-plugin](https://github.com/typeetfunc/babel-plugin-datascript)  for precompile and check static DataScript query.
Sorry for the lack of documentation and examples. Tomorrow I will add relevant examples of use.

**Comment by kristianmandrup** [comment]
Excellent :) Please do! Thanks!

**Comment by typeetfunc** [comment]
@ashnur @kristianmandrup I added some examples in [test directory](https://github.com/typeetfunc/datascript-mori/tree/master/release-js/test)
- [combineJsAndCljsApi.spec.js](https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test/combineJsAndCljsApi.spec.js) - this example demonstrated how to combine JS API with CLJS call [d.q() to get mori values](https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test/combineJsAndCljsApi.spec.js#L48)
- [onlyCljsApiUsage.spec.js](https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test/onlyCljsApiUsage.spec.js) - this example demonstrated how to use only CLJS API without any conversion(only mori.parse for parsing EDN string)

If you have any questions, ideas or are necessary more examples, let me know. I want to write docs, and I'd like know, which parts of API need to described in detail.

**Comment by kristianmandrup** [comment]
Thanks @typeetfunc :)
Does it simply wrap the final result of the query with a mori data structure or something more integrated/advanced? what are the performance stats?

I took the liberty to add your examples to the Datascript js wiki page
https://github.com/tonsky/datascript/wiki/Javascript-API

**Comment by typeetfunc** [comment]
> Does it simply wrap the final result of the query with a mori data structure or something more integrated/advanced? what are the performance stats?

No, I have not any benchmark(because build good benchmark is very hard), but I think that the absence of any conversions in runtime is very good for perfomance.

> something more integrated/advanced

For example? Mori is very powerful library, but it is lacks strandart lenses(see [ramdajs](http://ramdajs.com/0.19.1/docs/#lens)) and Option-wrappers(see [Option](https://github.com/fantasyland/fantasy-options) or [Optional](https://github.com/JasonStorey/Optional.js)). I want to create library with standart lenses and Option helpers for Mori.

> I took the liberty to add your examples to the Datascript js wiki page

@kristianmandrup Wow, Thanks! :)

**Comment by ashnur** [comment]
Thank you @typeetfunc both for the module and for the examples. They are really great, and I've been using them for several days now. 

One thing still bothers me a bit with this whole datascript + mori api. I wish I could have a lazy mori thing instead of the datascript entity, because:
1. it often runs into infinite recursion and dies with Maximum call stack size exceeded when I am doing a .toJs() call on it, even though I think it should stop
2. the interface is very confusing to use, sometimes it's `mori.get(...)` othertimes it's `entityValue.get(...)`
3. and it's even worse with mori.map, i can't use it over entities because that's just a javascript array which contains the actual mori objects and if I use it, then it doesn't get automatically extracted with `toJs`.

I know it's all a bit vague and I should give actual code instead of prose. I will try to come back to this issue and extend it with more concrete/specific data.

**Comment by kristianmandrup** [comment]
Hi ;) Thanks a lot as well!

@typeetfunc You are welcome to help create a good Datascript tutorial/book here including multiple integration guides:
https://github.com/kristianmandrup/datascript-tutorial/blob/master/Mori%20integration.md

@ashnur @typeetfunc : You are both most welcome to chip in on JS integration/use: https://github.com/kristianmandrup/datascript-tutorial/blob/master/Javascript%20integration.md

Cheers!

**Comment by typeetfunc** [comment]
@ashnur 

> the interface is very confusing to use, sometimes it's mori.get(...) othertimes it's entityValue.get(...)

Invocations `mori.get(entity, attr)` and `entity.get(attr)` is equal - https://tonicdev.com/parabellum06-94/56f690eb9075a811009fc414

> and it's even worse with mori.map, i can't use it over entities because that's just a javascript array which contains the actual mori objects and if I use it, then it doesn't get automatically extracted with toJs.

Can you provide an example?

> it often runs into infinite recursion and dies with Maximum call stack size exceeded when I am doing a .toJs() call on it, even though I think it should stop

maybe it's a bug in datascript? can you provide reproducible test case?

**Comment by typeetfunc** [comment]
@kristianmandrup Wow! Great work! I add more information about the mori integration soon.

**Comment by ashnur** [comment]
> Invocations mori.get(entity, attr) and entity.get(attr) is equal - https://tonicdev.com/parabellum06-94/56f690eb9075a811009fc414

Equal in result, but equal in invocation too? Is it sure that in 100% of the cases it's irrelevant which one I use?

**Comment by typeetfunc** [comment]
OK, you are right - its not fully equvalent.
`mori.get` call [lookup](https://github.com/tonsky/datascript/blob/master/src%2Fdatascript%2Fimpl%2Fentity.cljc#L101) function from definition ILookup protocol.
`entity.get` call [this function](https://github.com/tonsky/datascript/blob/master/src%2Fdatascript%2Fimpl%2Fentity.cljc#L63).
Hence `entity.get(attr)` completely equivalent `mori.get(entity, mori.toCljs(attr))`. You can avoid this conversion everywhere use only mori values instead JS values.

**Comment by ashnur** [comment]
Thank you again for the very detailed answer!
