### ISSUE TITLE
Documentation and usage

### ISSUE THREAD

**Issue by kristianmandrup** [typeetfunc/datascript-mori#2]
I would love to see the README expanded with links to your new test examples and some more explanations for when/how to use this library and the rationale behind it. 

Also if you could, please include some info on how you see it used in a real life (React) app ;)

Thanks :)

PS: Also not sure about how to use the babel-plugin you mentioned for a real world use case. Perhaps create a `datascript-mori-react-app` example in a separate repo?

**Comment by typeetfunc** [comment]
@kristianmandrup You are absolutely right! Soon I will add to the README examples and motivation for using.

> Perhaps create a datascript-mori-react-app example in a separate repo?

This project(and other related) were made to use in one React-DataScript application - I want to make Datascript-Devtools(like Redux-Devtools) for inspect and manage Datascript db in any application(with time travel(remote and local)). I think this is would good example and useful app :) 
But I will use [Rxjs with Datascript](https://github.com/typeetfunc/rx-datascript), that probably is not very good for example App. I'll think about a simpler example App. Maybe simple ToDoMVC? What do you think about it?

**Comment by kristianmandrup** [comment]
Thanks @typeetfunc :)

I've been building a slush TypeScript React generator, and would like to build a sub- generator for adding Datascript/Mori to a React app.

https://github.com/kristianmandrup/slush-react-ts

RxJs, ah yes. I should add that as well. Maybe we can collaborate. Did you think about or look into using TypeScript? Just like ES6 with types, enums and other goodies... (all optional)

**Comment by typeetfunc** [comment]
@kristianmandrup  I have updated [README](https://github.com/typeetfunc/datascript-mori/blob/master/README.md). What do you think about new README?

[You project](https://github.com/kristianmandrup/slush-react-ts) is very insterested. Also Typescript looks good. I can try to add WIP version of sub-generator for React App with `datascript-mori`.

**Comment by kristianmandrup** [comment]
Very nice! So much better :)
