### ISSUE TITLE
never version of datascript?

### ISSUE THREAD

**Issue by uds** [typeetfunc/datascript-mori#3]
Are there plans to update NPM with never version of bundled datascript?

**Comment by ashnur** [comment]
Maybe we have to fork it? I am also looking forward using the new features from datascript.

**Comment by typeetfunc** [comment]
@uds  @ashnur  Done!
0.16.1 on NPM or https://github.com/typeetfunc/datascript-mori/releases/tag/0.16.1

**Comment by kylecordes** [comment]
@typeetfunc It is surprising to see the published version uses 0.16.1, but the source code here in the repo still uses to `[datascript "0.15.4"]`. Did you `npm publish` but forget to `git push`?

**Comment by typeetfunc** [comment]
@kylecordes No. datascript-mori version and datascript version dont match. On October 21, the current version of datascript was 0.15.4. Today I will update datascript in datascript-mori to actual version(0.16.1).

**Comment by typeetfunc** [comment]
@kylecordes Released in https://github.com/typeetfunc/datascript-mori/releases/tag/0.17.0
