### ISSUE TITLE
Can't find db.fn/cas

### ISSUE THREAD

**Issue by ashnur** [typeetfunc/datascript-mori#4]
How to do compare-and-swap? I can't find it anywhere. Tried multiple ways and gives back `Unknown operation`

**Comment by typeetfunc** [comment]
@ashnur I add test for this case and export of db.fn/cas keyword. See tests:
1) JS API - https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test/combineJsAndCljsApi.spec.js#L53
2) CLJS API - https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test/onlyCljsApiUsage.spec.js#L132
