### ISSUE TITLE
Serialization to file

### ISSUE THREAD

**Issue by jonasseglare** [typeetfunc/datascript-mori#5]
This issue might be off-topic, but I am developing a Node.js application. How can I easiest serialize/deserialize the database to/from a file? This is useful for saving the application state, so that I can restore it later.

Thank you for providing this library.

**Comment by typeetfunc** [comment]
@jonasseglare I add simple support of datascript.transit in datascript-mori. See tests: https://github.com/typeetfunc/datascript-mori/blob/master/release-js/test/onlyCljsApiUsage.spec.js#L132
