### ISSUE TITLE
DataScript 0.16.0 removed ^:exports from datascript.core

### ISSUE THREAD

**Issue by tonsky** [typeetfunc/datascript-mori#6]
As of DataScript 0.16.0 I’ve [removed externs](https://github.com/tonsky/datascript/commit/130e06f87aff3269b25a43c458709903cc39858b) from `datascript.core` as they were disabling dead code elimination (see https://github.com/tonsky/datascript/issues/191). If you want to continue using `datascript.core` directly from JS, just add externs file when building `datascript-mori`

**Comment by typeetfunc** [comment]
@tonsky Thanks for issue! :) 
Fixed in https://github.com/typeetfunc/datascript-mori/commit/231be1db9890b720f7e65d00ec98048e348d3ee3
Released in https://github.com/typeetfunc/datascript-mori/releases/tag/0.17.0
