### ISSUE TITLE
Up to date versions?

### ISSUE THREAD

**Issue by kylecordes** [typeetfunc/datascript-mori#8]
Hello. I'm curious if this library is still in use - the versions of both Clojure and Datascript are behind. I try to trivial upgrade and hit errors...  before digging in, if it turns out there is an upgrade sitting out there that just hasn't been pushed yet, I would be pleased to obtain it. :-)

**Comment by ashnur** [comment]
@typeetfunc How about creating a group of people who would be able to update this project so we don't have to rely on you? :) Or any other solution would be nice, I don't really like opening new issues every couple of datascript updates :)

**Comment by ashnur** [comment]
Seems like we are going to need a better approach for this problem.

**Comment by typeetfunc** [comment]
@ashnur I add you to collaborators. check invite:)

**Comment by ashnur** [comment]
Now the question is, how to know if what I build actually works?

**Comment by kylecordes** [comment]
Thank you!
