### ISSUE TITLE
Can't build the the npm module

### ISSUE THREAD

**Issue by bahulneel** [typeetfunc/datascript-mori#9]
Hi,

I'm trying to update my clone of datascript-mori to more recent versions of datascript and cljs. However, I'm having issue building the JS even before updating the version numbers.

I get the error:
```bash
  var db = d.empty_db(scheme);
             ^

TypeError: Cannot read property 'empty_db' of undefined
```

which seems to be an issue with exporting datascript.core:
```js
> let dsm = require('./datascript-mori.js');
undefined
> Object.keys(dsm.datascript)
[ 'db', 'impl', 'js' ]
>
```

Any ideas what I'm doing wrong?

**Comment by ashnur** [comment]
Which versions are you trying? Care to share the `project.clj` please? I tried to update before but couldn't test it and now I can't even build it and I am trying to debug it.

**Comment by bahulneel** [comment]
I'm trying to build from the master branch. I seem to be having the same issue as you.

**Comment by bahulneel** [comment]
To add more info, I have the same issue with tags 0.17.0 and 0.16.1

**Comment by ashnur** [comment]
If you have the same issue then it's quite possible that we need to update the exports, datascript has changed what it exports and it might be that there is a mismatch. (I am only guessing, but will try later today again). Maybe between the both of us we can update this :)
